/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nova_novapro_MainActivity */

#ifndef _Included_com_nova_novapro_MainActivity
#define _Included_com_nova_novapro_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nova_novapro_MainActivity
 * Method:    StringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nova_novapro_MainActivity_StringFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_nova_novapro_MainActivity
 * Method:    Jpeg2Bmp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nova_novapro_MainActivity_Jpeg2Bmp
  (JNIEnv *, jobject);

/*
 * Class:     com_nova_novapro_MainActivity
 * Method:    TransImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nova_novapro_MainActivity_TransImage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
